### ISSUE TITLE
Create a testbed for comparing individual aerosol processes between Haero and mam_refactor

### ISSUE THREAD

**Issue by jeff-cohere** [eagles-project/haero#139]
One of the most challenging parts of this project is the lack of a verification methodology rooted in principles of basic physics and mathematics. As a result, existing analysis relies on validation in the form of low-fidelity "eyeball norm" metrics, sprinkled with arguments about statistical properties of various quantities. This kind of validation is not at all rigorous and leans heavily on subjective expert judgement, and poses a great challenge for any project that aims to displace a legacy model which has undergone enough validation to be accepted by researchers. How do we address it?

We can start by attempting to provide an apples-to-apples comparison between the implementation of each aerosol process in MAM with its counterpart in Haero. What do we mean by "apples-to-apples"? Basically, we want to be able to inspect output data from each process implementation in the most even-handed way possible so we can reason about any differences that we find. We do expect to find differences, because we are not adopting the bit-for-bit-identical approach used by some other modernization efforts. 

## Why not check that results are bit-for-bit identical between process implementations?

The bit-for-bit approach does give a definitive answer as to whether two process implementations are equivalent, but

1. it's extremely expensive in terms of human labor
2. it replicates any existing bugs or bad numerics in the prior implementations, no matter how egregious
3. it does not advance our understanding of the physical process. In fact, in our multi-language and multi-platform circumstances, it impedes this understanding by making us focus on the behavior of persnickety mathematical functions as they are expressed in Fortran, C++, or CUDA, instead of making scientific or quantitative arguments. 

At best, bit-for-bit identical implementations only delay the inevitable move toward better understanding and proper verification. At worst, they're a collosal waste of time and effort.

## Quasi-quantitative comparisons

Given the lack of underlying principles we have with which to evaluate the correctness of aerosol processes, we can focus initially on how different the outputs are from Haero and from the MAM box model. This means we need data from both implementations in the same format, preferably amenable for use with tools that help us view and quantify differences. The data should contain output from a range of input parameters, preferable those to which a process of interest is most sensitive. In many cases, the processes of interest are sensitive only to a handful of input variables.

A testbed for comparing a specific aerosol process over a range of parameters spanning a low-dimensional space could perform short single-process calculations (over one or a handful of time steps, perhaps) for each set of input values, and write them out in a way that makes it easy to access each output variable of interest relative to its input, and to visualize and compare it alongside data from the other implementation. This means we need two testbed programs: one for Haero, and one for the MAM box model. The two programs should take identical input that specifies the aerosol process and parameter space to be traversed, and they should write output in the same format for easy comparison.

## Input format

Here's a sample YAML file that we can use for inspiration. It specifies (in `process`) that the nucleation process is to be used (in both Haero and MAM), and gives a 3-parameter space (in `parameters`) for that process to traverse. Both the Haero and MAM box model testbeds accept this input file and run simulations appropriately:

```
process:
  mam: newnuc
  haero: MAMNucleationFProcess

timestepping:
  dt: 3600
  nsteps: 1

parameters:
  temperature: [270, 276, 0.5]
  relative_humidity: [0, 1, 0.1]
  qh2so4: [0, 1.e-3, 1.e-4]

atmosphere:
  temperature: 273
  pressure: 100000
  relative_humidity: 0.95
  height: 3000
  cloud_fraction: 0.0

aerosols:
  accumulation:
    number_conc: 1.e8
    so4: 0.3
    pom: 0
    soa: 0.3
    bc: 0
    dst: 0
    ncl: 0.4
    mom: 0
  aitken:
    number_conc: 1.e9
    so4: 0.3
    soa: 0.3
    ncl: 0.4
    mom: 0
  coarse:
    number_conc: 1.e5
    so4: 0.3
    pom: 0
    soa: 0.3
    bc: 0
    dst: 0
    ncl: 0.4
  primary_carbon:
    number_conc: 2.e8
    pom: 0
    bc: 1
    mom: 0

gases:
  qso2: 1.e-4
  qh2so4: 1.e-13
  qsoag: 5.e-10
```

## Output format

What format to use? Python and NetCDF are both popular options for storing climate data. Since we're not talking about a lot of data, it might be easier to write the data to a Python module that can be accessed via a script using e.g. matplotlib. If we were comparing the data to climate model data instead of data from individual processes, NetCDF might make more sense.

Such an "output module" could be expressed in terms of named variables storing Python lists or `numpy` arrays.
